name: Correr Scraper Home Depot

on:
  workflow_dispatch:
  schedule:
    - cron: '15 17 * * *'

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar Google Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ejecutar scraper
        env:
          APPS_SCRIPT_URL: https://script.google.com/macros/s/AKfycbyxBWMJvT50Xcq_LoR7xDca41iNP9Zwo5ERKgrq-V5M28eiulNl5jMvw_ko8REv-pn5/exec
        run: python main.py
